version: "3"
services:
  app:
    image: node:8
    volumes:
      - ./app:/home/app
    working_dir: /home/app
    ports:
      - 3007:8080
      - 3008:5000
    tty: true
    command: npm run serve
